# Generated by Django 5.2.7 on 2025-11-06 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifyapp.song')),
            ],
        ),
    ]
